In [38]:
import pandas as pd
import numpy as np
from datetime import datetime

In [39]:
df=pd.read_csv("anime.csv")

In [40]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [41]:
# FINDING EPISODES ADDING EXTRA COLUM

In [42]:
df.loc[1]["Title"]

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [43]:
def epi(txt):
    a=txt.find("(")
    b=txt.find(")")
    a=a+1
    l=txt[a:b]
    return l

In [44]:
df["Episodes"]=df["Title"].apply(epi)

In [45]:
df['Episodes']= df['Episodes'].str.replace(" eps","")
df.head(2) # removing the eps with blank

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24

In [46]:
# TOP EPISODE COUNT

In [47]:
df[df["Episodes"] == df["Episodes"].max()]

    Rank                                              Title  Score Episodes
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76       75

In [48]:
#TOP % EPISODE COUNT

In [49]:
df.sort_values(by="Episodes", ascending=False).head(5)

    Rank                                              Title  Score Episodes
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76       75
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87       74
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88        7
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51

In [50]:
def e(txt):
    a=txt.find(")")
    a=a+1
    l=txt[a:a+19]
    return l

In [51]:
df["Total Time"]=df["Title"].apply(e)

In [52]:
df.head()

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [53]:
# HIGHEST SCORING ANIME

In [54]:
df[df["Score"]==df["Score"].max()]

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010

In [55]:
# TO 5 HIGHEST SCORING ANIME

In [56]:
df.sort_values(by="Score", ascending=False).head()[["Title","Score"]]

                                               Title  Score
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [57]:
# TOTAL TIME NEW COLOUM

In [58]:
def mon(x):
    a=x.split("-")
    start=pd.to_datetime(a[0])
    end=pd.to_datetime(a[1])
    result=(end.year-start.year)*12+end.month-start.month+1
    return result
mon("Apr 2009 - Jul 2010")

16

In [59]:
df["Months"]=df["Total Time"].apply(mon)

In [66]:
# LONGEST RUNNING ANIME

In [67]:
df.loc[df["Months"].idxmax()]

Rank                                                         12
Title         Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
Score                                                      9.02
Episodes                                                    110
Total Time                                  Jan 1988 - Mar 1997
Months                                                      111
Name: 11, dtype: object

In [68]:
df.head(5)

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4